name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Install Expo CLI
        run: npm install -g expo-cli

      - name: Log in to Expo
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: expo login --token $EXPO_TOKEN

      - name: Build APK
        run: expo build:android --no-wait

      - name: Wait for build to complete
        run: |
          ID=$(expo build:status | grep -oP '(?<=id":")[^"]+')
          URL="https://expo.io/artifacts/${ID}"
          echo $URL
        shell: bash 

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: ./path/to/downloaded/apk
